# Generated by Django 5.2.5 on 2025-09-05 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AnalyticsModel', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ErrorLog',
        ),
    ]
