# Generated by Django 5.2.5 on 2025-09-05 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnalyticsModel', '0002_delete_errorlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemmetrics',
            name='total_memory_gb',
            field=models.FloatField(default=32),
            preserve_default=False,
        ),
    ]
