# Generated by Django 5.2.3 on 2025-09-06 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnalyticsModel', '0003_systemmetrics_total_memory_gb'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemmetrics',
            name='gpu_memory_usage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemmetrics',
            name='gpu_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='systemmetrics',
            name='gpu_temperature',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemmetrics',
            name='gpu_total_memory_gb',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
