# Generated by Django 5.2.3 on 2025-09-03 11:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LogModel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='api_endpoint',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='log',
            name='error_category',
            field=models.CharField(choices=[('none', 'None'), ('validation', 'Validation Error'), ('authentication', 'Authentication Error'), ('permission', 'Permission Error'), ('not_found', 'Not Found'), ('server', 'Server Error'), ('database', 'Database Error'), ('external_api', 'External API Error'), ('business_logic', 'Business Logic Error'), ('unknown', 'Unknown Error')], default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='log',
            name='full_file_path',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='log',
            name='http_method',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='log',
            name='is_error',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='log',
            name='request_path',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='log',
            name='user_agent',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='log',
            name='user_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='level',
            field=models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical'), ('debug', 'Debug')], default='error', max_length=20),
        ),
        migrations.AddIndex(
            model_name='log',
            index=models.Index(fields=['-timestamp'], name='LogModel_lo_timesta_4402cf_idx'),
        ),
        migrations.AddIndex(
            model_name='log',
            index=models.Index(fields=['user', '-timestamp'], name='LogModel_lo_user_id_de59e5_idx'),
        ),
        migrations.AddIndex(
            model_name='log',
            index=models.Index(fields=['level', '-timestamp'], name='LogModel_lo_level_a33742_idx'),
        ),
        migrations.AddIndex(
            model_name='log',
            index=models.Index(fields=['is_error', '-timestamp'], name='LogModel_lo_is_erro_3302ca_idx'),
        ),
    ]
