# Generated by Django 5.2.5 on 2025-08-15 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expired_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'User Auth',
                'verbose_name_plural': 'User Auth',
                'ordering': ['-created_at'],
            },
        ),
    ]
