# Generated by Django 5.2.5 on 2025-08-15 09:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Connect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('type', models.CharField(choices=[('app', 'App Credential'), ('admin', 'Admin Credential'), ('user', 'User Credential'), ('none', 'No Credentail')], default='app', max_length=10)),
                ('name', models.CharField(default='', max_length=20)),
                ('desc', models.CharField(default='', max_length=255)),
                ('token', models.CharField(default='c837649cce43f27257378096', max_length=34, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Connect',
                'verbose_name_plural': 'Connects',
                'ordering': ['-created_at'],
            },
        ),
    ]
