# Generated by Django 5.2.5 on 2025-08-15 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConnectModel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connect',
            name='token',
            field=models.CharField(default='0e17daca5f3e175f49173546', max_length=34, unique=True),
        ),
    ]
