# Generated by Django 5.2.5 on 2025-08-15 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConnectModel', '0002_alter_connect_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connect',
            name='token',
            field=models.CharField(default='4ec9599fc203d17618904533', max_length=34, unique=True),
        ),
    ]
