# Generated by Django 5.2.5 on 2025-08-15 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConnectModel', '0003_alter_connect_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connect',
            name='token',
            field=models.CharField(default='0b918943df0962bc39693364', max_length=34, unique=True),
        ),
    ]
