# Generated by Django 5.2.3 on 2025-08-21 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConnectModel', '0004_alter_connect_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connect',
            name='token',
            field=models.CharField(default='9f14025af0065b3035625710', max_length=34, unique=True),
        ),
    ]
