# Generated by Django 5.2.3 on 2025-08-21 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConnectModel', '0006_alter_connect_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connect',
            name='token',
            field=models.CharField(default='71ee45a3c0db9a9844518028', max_length=34, unique=True),
        ),
    ]
