# Generated by Django 5.2.3 on 2025-09-03 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConnectModel', '0011_alter_connect_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connect',
            name='token',
            field=models.CharField(default='c837649cce43f2725764240', max_length=34, unique=True),
        ),
    ]
