# Generated by Django 5.2.3 on 2025-09-03 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConnectModel', '0013_alter_connect_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connect',
            name='token',
            field=models.CharField(default='31489056e0916d5947396591', max_length=34, unique=True),
        ),
    ]
