# Generated by Django 5.2.3 on 2025-09-03 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConnectModel', '0014_alter_connect_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connect',
            name='token',
            field=models.CharField(default='d4735e3a265e16ee2197238', max_length=34, unique=True),
        ),
    ]
