# Generated by Django 5.2.3 on 2025-09-03 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConnectModel', '0015_alter_connect_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connect',
            name='token',
            field=models.CharField(default='aea92132c4cbeb2638867568', max_length=34, unique=True),
        ),
    ]
