# Generated by Django 5.2.3 on 2025-09-03 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConnectModel', '0018_alter_connect_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connect',
            name='token',
            field=models.CharField(default='9400f1b21cb527d719261438', max_length=34, unique=True),
        ),
    ]
