# Generated by Django 5.2.5 on 2025-09-05 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConnectModel', '0019_alter_connect_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connect',
            name='token',
            field=models.CharField(default='c837649cce43f27257966425', max_length=34, unique=True),
        ),
    ]
