# Generated by Django 5.2.5 on 2025-09-05 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConnectModel', '0020_alter_connect_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connect',
            name='token',
            field=models.CharField(default='670671cd9740415627722942', max_length=34, unique=True),
        ),
    ]
