# Generated by Django 5.2.3 on 2025-07-07 06:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlackList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('blacklist_type', models.CharField(choices=[('ip', 'IP Address'), ('user', 'User Account'), ('both', 'IP and User')], default='ip', max_length=10)),
                ('reason', models.CharField(choices=[('rate_limit_abuse', 'Rate Limit Abuse'), ('suspicious_activity', 'Suspicious Activity'), ('security_violation', 'Security Violation'), ('spam', 'Spam/Bot Activity'), ('manual', 'Manual Block'), ('automated', 'Automated Detection')], default='rate_limit_abuse', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_permanent', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('violation_count', models.IntegerField(default=1)),
                ('last_violation', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(default='system', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['ip_address', 'is_active'], name='RateLimitMo_ip_addr_afaa60_idx'), models.Index(fields=['user', 'is_active'], name='RateLimitMo_user_id_0dd36e_idx'), models.Index(fields=['expires_at', 'is_active'], name='RateLimitMo_expires_60163a_idx')],
                'unique_together': {('ip_address', 'user', 'blacklist_type')},
            },
        ),
        migrations.CreateModel(
            name='RateLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('endpoint', models.CharField(default='api_general', max_length=50)),
                ('request_count', models.IntegerField(default=1)),
                ('window_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['ip_address', 'endpoint', 'window_start'], name='RateLimitMo_ip_addr_8d0326_idx'), models.Index(fields=['user', 'endpoint', 'window_start'], name='RateLimitMo_user_id_8bf1e1_idx')],
                'unique_together': {('ip_address', 'user', 'endpoint', 'window_start')},
            },
        ),
        migrations.CreateModel(
            name='WhiteList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('whitelist_type', models.CharField(choices=[('ip', 'IP Address'), ('user', 'User Account'), ('both', 'IP and User')], default='ip', max_length=10)),
                ('reason', models.CharField(choices=[('trusted_user', 'Trusted User'), ('admin_user', 'Administrator'), ('api_service', 'API Service'), ('internal_system', 'Internal System'), ('vip_user', 'VIP User'), ('testing', 'Testing Purpose'), ('manual', 'Manual Whitelist'), ('automated', 'Automated Whitelist')], default='trusted_user', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_permanent', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('usage_count', models.IntegerField(default=0)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(default='system', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('bypass_rate_limits', models.BooleanField(default=True, help_text='Bypass all rate limiting')),
                ('custom_rate_multiplier', models.FloatField(default=1.0, help_text='Rate limit multiplier (e.g., 2.0 = double the limits)')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'White List',
                'verbose_name_plural': 'White Lists',
                'indexes': [models.Index(fields=['ip_address', 'is_active'], name='RateLimitMo_ip_addr_ef8a70_idx'), models.Index(fields=['user', 'is_active'], name='RateLimitMo_user_id_a9dbd5_idx'), models.Index(fields=['expires_at', 'is_active'], name='RateLimitMo_expires_a588f8_idx')],
                'unique_together': {('ip_address', 'user', 'whitelist_type')},
            },
        ),
    ]
