# Generated by Django 5.2.5 on 2025-08-15 09:52

import SsoModel.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppServiceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desc', models.TextField(default='')),
                ('app_uuid', models.UUIDField(default=uuid.uuid4)),
                ('app_token', models.CharField(max_length=32)),
                ('route_config', models.JSONField(default=SsoModel.models.default_route_config)),
                ('service_core', models.CharField(choices=[('message', 'Message Core'), ('exchange', 'Exchange Core'), ('user_management', 'User Management Core'), ('market', 'Market Core'), ('news', 'News Core')], default='message', max_length=20)),
                ('credential_type', models.CharField(choices=[('app', 'App Credential'), ('admin', 'Admin Credential'), ('user', 'User Credential'), ('none', 'No Credentail')], default='app', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'App Service Provider',
                'verbose_name_plural': 'App Service Providers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SsoUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asp_user_uuid', models.UUIDField(default=uuid.uuid4)),
                ('asp_user_token', models.CharField(max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('last_access_at', models.DateTimeField(auto_now=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('asp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SsoModel.appserviceprovider')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'asp')},
            },
        ),
    ]
